services:
#    alala_moviedb.example:
#        class: Alala\MoviedbBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    alala_moviedb.movie_loader_tmdb:
        class: Alala\MoviedbBundle\Service\MovieLoaderTmdb
        arguments:
            $em: '@doctrine.orm.entity_manager'
        